if [ -d "${CUSTOMDIR}/bin" ] ; then
   export PATH="$CUSTOMDIR/bin:${PATH}"
fi

#golang
if [ -d ${CUSTOMDIR}/golang ]; then
    export GOROOT=${CUSTOMDIR}/golang/go
    export PATH=${PATH}:${GOROOT}/bin
fi
if [ -d ${HOME}/golang ]; then
    export GO111MODULE=auto
    export GOPATH=${HOME}/golang
    export PATH=${PATH}:${GOPATH}/bin
fi

if [ -d /usr/local/go/bin ]; then
    export PATH=${PATH}:/usr/local/go/bin
fi
